### ISSUE TITLE
CLI Publishing, how does it work?

### ISSUE THREAD

**Issue by AcidRaZor** [nyaggah/bedframe#560]
Currently in the trenches, some of the dev team built pipelines around directly interacting with gcloud to automate publishing, but I was under the impression bedframe would handle publishing via the CLI?

Trying to write-up a prototype to show people how it works, but can't find any docs on what is required for the publish step to work?

TIA

**Comment by JoeyDoey** [comment]
Hey @AcidRaZor ! thanks for checking out Bedframe.

Apologies! Full documentation is still WIP but hopefully the following can help you along.

Yeah, you should be able to publish via the CLI... but it needs access to the env. Either in CI (in the workflow file) or via .env file. The Bedframe CLI publish command just has an option to pass in the browser you want to publish (and will pick up the available env vars that way).

E.g. in CI, the workflow will run the `bedframe publish` command as follows:

```yml
      - name: '[ P U B L I S H ] : Chrome - upload to Chrome Web Store'
        id: publishChrome
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: npm run publish chrome
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          PACKAGE_NAME: ${{ steps.package.outputs.PACKAGE_NAME }}
          PACKAGE_VERSION: ${{ steps.package.outputs.PACKAGE_VERSION }}

      - name: 'Firefox - upload to AMO'
        id: publishFirefox
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: npm run publish firefox
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
          PACKAGE_NAME: ${{ steps.package.outputs.PACKAGE_NAME }}
          PACKAGE_VERSION: ${{ steps.package.outputs.PACKAGE_VERSION }}

      - name: 'MS Edge - upload to MS Edge Add-ons'
        id: publishEdge
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: npm run publish edge
        env:
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_CLIENT_SECRET: ${{ secrets.EDGE_CLIENT_SECRET }}
          PACKAGE_NAME: ${{ steps.package.outputs.PACKAGE_NAME }}
          PACKAGE_VERSION: ${{ steps.package.outputs.PACKAGE_VERSION }}
```

The above is assuming the project's `package.json` has script for publish like so:

```json
  "publish": "bedframe publish -b"
```

Run `bedframe publish --help` to see publish command options.

Take a look at the code for [Bedframe CLI's publish command](https://github.com/nyaggah/bedframe/blob/main/packages/cli/src/commands/publish.ts). What each function does and expects should be roughly outlined in the function comments. Take a look at the comments above `uploadToChrome`, `uploadToFirefox`, and `uploadToEdge` funcs. 

Also take a quick look at the [example .env](https://github.com/nyaggah/bedframe/blob/main/examples/popup-react-ts/__env.example) for the env vars you'd need to publish from the command line.


But to get you unstuck, under the hood, bedframe is just using the following utilities in case you want to do it directly:

- publishing to Chrome: [chrome-webstore-upload-cli](https://www.npmjs.com/package/chrome-webstore-upload-cli)
- publishing to Firefox: [Web Ext](https://www.npmjs.com/package/web-ext)
- publishing to Edge: [Edge REST API](https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/api/using-addons-api?tabs=v1-1)
